apps/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('adicionar/', views.add_cliente, name='add_cliente'),
    path('', views.list_clientes, name='list_clientes'),
    path('editar/<int:id_cliente>/', views.edit_cliente, name='edit_cliente'),
    path('excluir/<int:id_cliente>/', views.delete_cliente, name='delete_cliente'),
    path('buscar/', views.search_clientes, name='search_clientes'),
]

apps/emprestimos/urls.py
from django.urls import path
from . import views

app_name = 'emprestimos'

urlpatterns = [
    path('', views.list_emprestimos, name='list_emprestimos'),
    path('adicionar/<int:id_cliente>/', views.add_emprestimo, name='add_emprestimo'),
    path('excluir/<int:id_emprestimo>/', views.delete_emprestimo, name='delete_emprestimo'),
    path('excluir-item/<int:id_emprestimo_item>/', views.delete_emprestimo_item, name='delete_emprestimo_item'),
    path('adicionar-item/<int:id_emprestimo>/', views.add_emprestimo_item, name='add_emprestimo_item'),
    path('editar-status/<int:id_emprestimo>/', views.edit_emprestimo_status, name='edit_emprestimo_status'),
]

bibliotecaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('bibliotecarios/', include('bibliotecarios.urls', namespace='bibliotecarios')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('autores/', include('autores.urls', namespace='autores')),
    path('editoras/', include('editoras.urls', namespace='editoras')),
    path('livros/', include('livros.urls', namespace='livros')),
    path('emprestimos/', include('emprestimos.urls', namespace='emprestimos')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/emprestimos/models.py
from django.db import models
from clientes.models import Cliente
from livros.models import Livro

# Create your models here.

class Emprestimo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    item_emprestimo = models.ManyToManyField(Livro, through='ItemEmprestimo', blank=True)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    
    class Meta:
        verbose_name = 'Emprestimo'
        verbose_name_plural = 'Emprestimos'
        ordering =['id']

    def __str__(self):
        return f"emprestimo de {self.cliente.last_name}"


class ItemEmprestimo(models.Model):
    emprestimo = models.ForeignKey(Emprestimo, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de emprestimo'
        verbose_name_plural = 'Itens de emprestimo'
        ordering =['id']

    def __str__(self):
        return self.livro.title

apps/emprestimos/forms.py
from django import forms
from .models import Emprestimo, Cliente, ItemEmprestimo ,Livro

class EmprestimoForm(forms.ModelForm):
    
    class Meta:
        model = Emprestimo
        exclude = ('cliente',)

class ItemEmprestimoForm(forms.ModelForm):
    
    class Meta:
        model = ItemEmprestimo
        exclude = ('emprestimo',)

apps/emprestimos/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import EmprestimoForm, ItemEmprestimoForm
from .models import Emprestimo , ItemEmprestimo, Livro, Cliente

# Create your views here.

def add_emprestimo(request, id_cliente):
    template_name = 'emprestimos/add_emprestimo.html'
    context = {}
    if request.method == 'POST':
        form = EmprestimoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.cliente = Cliente.objects.get(id=id_cliente)
            f.save()
            form.save_m2m()
            return redirect('emprestimos:list_emprestimos')
    form = EmprestimoForm()
    context['form'] = form
    return render(request, template_name, context)

def list_emprestimos(request):
    template_name = 'emprestimos/list_emprestimos.html'
    emprestimos = Emprestimo.objects.filter()
    emprestimo_items = ItemEmprestimo.objects.filter()
    livros = Livro.objects.filter()
    clientes = Cliente.objects.filter()
    context = {
        'emprestimos': emprestimos,
        'emprestimo_items': emprestimo_items,
        'livros': livros,
        'clientes': clientes
    }
    return render(request, template_name, context)

def delete_emprestimo(request, id_emprestimo):
    emprestimo = Emprestimo.objects.get(id=id_emprestimo)
    emprestimo.delete()
    return redirect('emprestimos:list_emprestimos')

def add_emprestimo_item(request, id_emprestimo):
    template_name = 'emprestimos/add_emprestimo_item.html'
    context = {}
    if request.method == 'POST':
        form = ItemEmprestimoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.emprestimo = Emprestimo.objects.get(id=id_emprestimo)
            f.save()
            form.save_m2m()
            return redirect('emprestimos:list_emprestimos')
    form = ItemEmprestimoForm()
    context['form'] = form
    return render(request, template_name, context)

def delete_emprestimo_item(request, id_emprestimo_item):
    emprestimoitem = ItemEmprestimo.objects.get(id=id_emprestimo_item)
    emprestimoitem.delete()
    return redirect('emprestimos:list_emprestimos')

def edit_emprestimo_status(request, id_emprestimo):
    template_name = 'emprestimos/edit_emprestimo_status.html'
    context ={}
    emprestimo = get_object_or_404(Emprestimo, id=id_emprestimo)
    if request.method == 'POST':
        form = EmprestimoForm(request.POST, instance=emprestimo)
        if form.is_valid():
            form.save()
            return redirect('emprestimos:list_emprestimos')
    form = EmprestimoForm(instance=emprestimo)
    context['form'] = form
    return render(request, template_name, context)

templates/emprestimos/add_emprestimo.html
{% extends 'base.html' %}

{% block title %}

    Abrir Emprestimo - {{ block.super }}

{% endblock title %}

{% block body %}

<br />
<br />
<b>Deseja abrir um emprestimo de livro? </b>
<form action="" method="POST">
{% csrf_token %}
    <button type="submit">Sim</button> <a href="{% url 'clientes:list_clientes' %}">Nao</a>     
</form>
<br />
<br />     

{% endblock body %}

templates/emprestimos/add_emprestimo_item.html
{% extends 'base.html' %}

{% block title %}

    Adicionar Item de Emprestimo - {{ block.super }}

{% endblock title %}

{% block body %}

{% load widget_tweaks %}

<br />
<b>Adicionar Item de Emprestimo</b>
<br />
<br />
<form action="" method="POST">
{% csrf_token %}                
    <label>Livro</label>
    <br /> 
    {{ form.livro|add_class:"form-control" }}
    <br /> 
    <br />        
    <button type="submit">Salvar</button>       
 </form>

{% endblock body %}

templates/emprestimos/edit_emprestimo_status.html
{% extends 'base.html' %}

{% block title %}

    Alterar Status do Emprestimo - {{ block.super }}

{% endblock title %}

{% block body %}

<br />
<b>Alterar Status do Emprestimo</b>
<br />
<br />
<form action="" method="POST">
{% csrf_token %}
    <label>Status</label>
    <br />
    {{ form.status }}
    <br />
    <br />
    <button type="submit">Alterar</button>       
</form>


{% endblock body %}

templates/emprestimos/list_emprestimos.html
{% extends 'base.html' %}

{% block title %}

    Lista de Emprestimos - {{ block.super }}

{% endblock title %}

{% block body %}

<br />
<b>Lista de Emprestimos</b>
<table border="1">
    <thead>
        <tr>
            <th>ID</th>
            <th>Status</th>
            <th>Cliente</th>
            <th>Itens de pedido</th>
            <th> -- </th>
            <th> -- </th>
        </tr>
    </thead>
    <tbody>
    {% for emprestimo in emprestimos %}
        <tr>
            <td>
                {% if emprestimo.status == 'Finalizado' or emprestimo.status == 'Cancelado' %}
                    <p style="color:darkgray;" >{{ emprestimo.id }}</p>
                {% else %}
                    {{ emprestimo.id }}
                {% endif %}
            </td>
            <td>
                {% if emprestimo.status == 'Finalizado' or emprestimo.status == 'Cancelado' %}
                    <p style="color:darkgray;" >{{ emprestimo.status }}</p>
                {% else %}
                    {{ emprestimo.status }}
                {% endif %}
             </td>
            <td>
                {% for cliente in clientes %}
                    {% if emprestimo.cliente_id == cliente.id %}
                        {% if emprestimo.status == 'Finalizado' or emprestimo.status == 'Cancelado' %}
                            <p style="color:darkgray;" >{{ cliente.first_name }} {{ cliente.last_name }}</p>
                        {% else %}
                            {{ cliente.first_name }} {{ cliente.last_name }}
                        {% endif %}
                    {% endif %}
                {% endfor %}   
            </td>
            <td>
                {% if emprestimo.status == 'Finalizado' or emprestimo.status == 'Cancelado' %}
                    <a href="#" class="btn btn-primary btn-sm disabled" style="color: darkgray;">Adicionar itens</a>
                {% else %}
                    <a href="{% url 'emprestimos:add_emprestimo_item' emprestimo.id %}" class="btn btn-primary btn-sm">Adicionar itens</a>
                {% endif %}
                <br />
                <br />
                {% for emprestimo_item in emprestimo_items %}
                    {% if emprestimo_item.emprestimo_id == emprestimo.id %}
                        Livro: {{ emprestimo_item.livro}}<br /> 
                        <a href="{% url 'emprestimos:delete_emprestimo_item' emprestimo_item.id %}">Excluir Item</a><br /><br />
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'emprestimos:edit_emprestimo_status' emprestimo.id %}">Alterar Status</a>
            </td>
            <td>
                <a href="{% url 'emprestimos:delete_emprestimo' emprestimo.id %}">Excluir</a>
            </td>
            </tr> 
        {% endfor %}
    </tbody>
</table>


{% endblock body %}