apps/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('adicionar/', views.add_cliente, name='add_cliente'),
    path('', views.list_clientes, name='list_clientes'),
    path('editar/<int:id_cliente>/', views.edit_cliente, name='edit_cliente'),
    path('excluir/<int:id_cliente>/', views.delete_cliente, name='delete_cliente'),
    path('buscar/', views.search_clientes, name='search_clientes'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('my_ip/', views.my_ip, name='my_ip'),
]

apps/livros/urls.py
from django.urls import path
from . import views

app_name = 'livros'

urlpatterns = [
    path('adicionar/', views.add_livro, name='add_livro'),
    path('', views.list_livros, name='list_livros'),
    path('editar/<int:id_livro>/', views.edit_livro, name='edit_livro'),
    path('excluir/<int:id_livro>/', views.delete_livro, name='delete_livro'),
]

bibliotecaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('bibliotecarios/', include('bibliotecarios.urls', namespace='bibliotecarios')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('autores/', include('autores.urls', namespace='autores')),
    path('editoras/', include('editoras.urls', namespace='editoras')),
    path('livros/', include('livros.urls', namespace='livros')),
    path('emprestimos/', include('emprestimos.urls', namespace='emprestimos')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests

# Create your views here.

def home(request):
    template_name ='core/home.html'
    context = {}
    return render(request, template_name, context)

def my_ip(request):
    try:
        import requests
        ip = requests.get('https://api.ipify.org', timeout=5).text
    except Exception as e:
        ip = f"Erro: {e}"
    return HttpResponse(f"Meu IP público: {ip}")

templates/core/home.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block body %}

{% load static %}

<!-- Codigo html especifico desse arquivo -->

<div class="home-container">
    <div class="home-left">
        <h3>Bem Vindo ao Biblioteca App.</h3>
        <h4>Ações rápidas:</h4>
        <div class="home-left-actions">
            <div class="home-left-actions-search">
                <form action="{% url 'clientes:search_clientes' %}" method="GET">
                    <input name="query" type="text" placeholder="Buscar cliente pelo sobrenome" aria-label="Buscar">
                    <button type="submit"><span class="material-symbols-outlined">search</span>Buscar</button>
                </form>
            </div>
            <a class="quick-btn" href="{% url 'clientes:list_clientes' %}"><span class="material-symbols-outlined">group</span>Listar Clientes</a>
            <a class="quick-btn" href="{% url 'clientes:add_cliente' %}"><span class="material-symbols-outlined">addgroup</span>Criar novo Cliente</a>
            <a class="quick-btn" href="{% url 'livros:list_livros' %}"><span class="material-symbols-outlined">menu_book</span>Ver Livros</a>
            <a class="quick-btn" href="{% url 'livros:add_livro' %}"><span class="material-symbols-outlined">addmenu_book</span>Adicionar um Livro</a>
        </div>
    </div>
    <div class="home-right">
        <img alt="Imagem Biblioteca" src="{% static 'img/biblioteca.webp' %}" />
    </div>
</div>

{% endblock body %}