apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

apps/autores/urls.py
from django.urls import path
from . import views

app_name = 'autores'

urlpatterns = [
    path('adicionar/', views.add_autor, name='add_autor'),
    path('', views.list_autores, name='list_autores'),
    path('editar/<int:id_autor>/', views.edit_autor, name='edit_autor'),
    path('excluir/<int:id_autor>/', views.delete_autor, name='delete_autor'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('my_ip/', views.my_ip, name='my_ip'),
]

apps/livros/urls.py
from django.urls import path
from . import views

app_name = 'livros'

urlpatterns = [
    path('adicionar/', views.add_livro, name='add_livro'),
    path('', views.list_livros, name='list_livros'),
    path('editar/<int:id_livro>/', views.edit_livro, name='edit_livro'),
    path('excluir/<int:id_livro>/', views.delete_livro, name='delete_livro'),
]

bibliotecaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('bibliotecarios/', include('bibliotecarios.urls', namespace='bibliotecarios')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('autores/', include('autores.urls', namespace='autores')),
    path('editoras/', include('editoras.urls', namespace='editoras')),
    path('livros/', include('livros.urls', namespace='livros')),
    path('emprestimos/', include('emprestimos.urls', namespace='emprestimos')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my-styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <title>{% block title %}Biblioteca App{% endblock title %}</title>
</head>
<body>
    <header>
        <div>
            <a href="{% url 'core:home' %}" ><button class="btn header-btn">Home</button></a>
            <div class="dropdown" style="display: inline-block;">
                <button class="btn header-btn dropdown-toggle" type="button" id="menuDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Conta
                </button>
                <div class="dropdown-menu" aria-labelledby="menuDropdown">
                    {% if user.is_authenticated %}
                        <!-- <a class="dropdown-item" href="#">{{ user.get_full_name|default:user.username }}</a> -->
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Alterar dados</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair de {{ user.get_full_name|default:user.username }}</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'accounts:user_login' %}">Entrar</a>
                    {% endif %}
                </div>
            </div>
            <div class="dropdown" style="display: inline-block;">
                <button class="btn header-btn dropdown-toggle" type="button" id="menuDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </button>
                <div class="dropdown-menu" aria-labelledby="menuDropdown">
                    <a class="dropdown-item" href="{% url 'clientes:list_clientes' %}">Clientes</a>
                    <a class="dropdown-item" href="{% url 'bibliotecarios:list_bibliotecarios' %}">Bibliotecarios</a>
                    <a class="dropdown-item" href="{% url 'categorias:list_categorias' %}">Categorias</a>
                    <a class="dropdown-item" href="{% url 'autores:list_autores' %}">Autores</a>
                    <a class="dropdown-item" href="{% url 'editoras:list_editoras' %}">Editoras</a>
                    <a class="dropdown-item" href="{% url 'livros:list_livros' %}">Livros</a>
                    <a class="dropdown-item" href="{% url 'emprestimos:list_emprestimos' %}">Emprestimos</a>
                </div>
            </div>
        </div>
        <div>
            <form action="{% url 'clientes:search_clientes' %}" method="GET">
                <input name="query" type="text" placeholder="Sobrenome do cliente" aria-label="Buscar">
                <button type="submit">Buscar</button>
            </form>
        </div>
    </header>
    <br />

    <div class="page_content">
        {% block body %}
        
        {% endblock body %}
    </div>
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>