apps/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('adicionar/', views.add_cliente, name='add_cliente'),
    path('', views.list_clientes, name='list_clientes'),
    path('editar/<int:id_cliente>/', views.edit_cliente, name='edit_cliente'),
    path('excluir/<int:id_cliente>/', views.delete_cliente, name='delete_cliente'),
    path('buscar/', views.search_clientes, name='search_clientes'),
]

apps/emprestimos/urls.py
from django.urls import path
from . import views

app_name = 'emprestimos'

urlpatterns = [
    path('', views.list_emprestimos, name='list_emprestimos'),
    path('adicionar/<int:id_cliente>/', views.add_emprestimo, name='add_emprestimo'),
    path('excluir/<int:id_emprestimo>/', views.delete_emprestimo, name='delete_emprestimo'),
    path('excluir-item/<int:id_emprestimo_item>/', views.delete_emprestimo_item, name='delete_emprestimo_item'),
    path('adicionar-item/<int:id_emprestimo>/', views.add_emprestimo_item, name='add_emprestimo_item'),
    path('editar-status/<int:id_emprestimo>/', views.edit_emprestimo_status, name='edit_emprestimo_status'),
]

bibliotecaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('bibliotecarios/', include('bibliotecarios.urls', namespace='bibliotecarios')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('autores/', include('autores.urls', namespace='autores')),
    path('editoras/', include('editoras.urls', namespace='editoras')),
    path('livros/', include('livros.urls', namespace='livros')),
    path('emprestimos/', include('emprestimos.urls', namespace='emprestimos')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=100) 
    email = models.EmailField('E-mail',null=False, blank=False)
    cell_phone = models.CharField('Telefone celular', max_length=20)
    address = models.CharField('Endereco', max_length=200)   
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering =['id']

    def __str__(self):
        return self.first_name

apps/clientes/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        exclude = ()

apps/clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import ClienteForm
from .models import Cliente

# Create your views here.

def add_cliente(request):
    template_name = 'clientes/add_cliente.html'
    context = {}
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('clientes:list_clientes')
    form = ClienteForm()
    context['form'] = form
    return render(request, template_name, context)

def list_clientes(request):
    template_name = 'clientes/list_clientes.html'
    clientes = Cliente.objects.filter()
    context = {
        'clientes': clientes
    }
    return render(request, template_name, context)

def edit_cliente(request, id_cliente):
    template_name = 'clientes/add_cliente.html'
    context ={}
    cliente = get_object_or_404(Cliente, id=id_cliente)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('clientes:list_clientes')
    form = ClienteForm(instance=cliente)
    context['form'] = form
    return render(request, template_name, context)

def delete_cliente(request, id_cliente):
    cliente = Cliente.objects.get(id=id_cliente)
    cliente.delete()
    return redirect('clientes:list_clientes')

def search_clientes(request):
    template_name = 'clientes/list_clientes.html'
    query = request.GET.get('query')
    clientes = Cliente.objects.filter(last_name__icontains=query)
    context = {
        'clientes': clientes,
    }
    return render(request,template_name, context)

templates/clientes/add_cliente.html
{% extends 'base.html' %}

{% block title %}
  Adicionar Cliente - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
  <b>Cadastro de Clientes</b>
  <br />
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    <label>Nome:</label>
    <br />
    {{ form.first_name }}
    <br />
    <label>Sobrenome:</label>
    <br />
    {{ form.last_name }}
    <br />
    <label>Celular:</label>
    <br />
    {{ form.cell_phone }}
    <br />
    <label>Email:</label>
    <br />
    {{ form.email }}
    <br />
    <label>Endereco:</label>
    <br />
    {{ form.address }}
    <br />
    <label>Genero:</label>
    <br />
    {{ form.gender }}
    <br />
    <br />
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientes/list_clientes.html
{% extends 'base.html' %}

{% block title %}
  Lista de Clientes - {{ block.super }}
{% endblock %}

{% block body %}
  <br />
    <a class="quick-btn" href="{% url 'clientes:add_cliente' %}"><span class="material-symbols-outlined">addgroup</span>Adicionar novo Cliente</a>
  <br />
  <br />
  <b>Lista de Clientes</b>
  <br />
  <br />
  <table border="1">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Sobrenome</th>
        <th scope="col">Celular</th>
        <th scope="col">Email</th>
        <th scope="col">Endereco</th>
        <th scope="col">Genero</th>
        <th scope="col">--</th>
        <th scope="col">--</th>
        <th scope="col">--</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
        <tr>
          <th>{{ cliente.id }}</th>
          <td>{{ cliente.first_name }}</td>
          <td>{{ cliente.last_name }}</td>
          <td>{{ cliente.cell_phone }}</td>
          <td>{{ cliente.email }}</td>
          <td>{{ cliente.address }}</td>
          <td>{{ cliente.gender }}</td>
          <td>
            <a href="{% url 'clientes:edit_cliente' cliente.id %}">Editar</a>
          </td>
          <td>
            <a href="{% url 'clientes:delete_cliente' cliente.id %}" >Excluir</a>
          </td>
          <td>   
            <a href="{% url 'emprestimos:add_emprestimo' cliente.id %}">Fazer Emprestimo</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}